Fix broken unit test
This change mocks sqlalchemy.update during unit tests properly to avoid
the following error.

sqlalchemy.exc.ArgumentError: subject table for an INSERT, UPDATE or
DELETE expected, got <MagicMock name='models.Instance' id='...'>

Closes-Bug: #1938676
Change-Id: I5268132018e0a283bd35b5599cf8ca41968dde93
(cherry picked from commit 2800f0b62c2936cd68c35623010c3f57d58b975d)