Fix compatibility with Python 3.10
Since testing with Python 3.10, the test
  murano.tests.unit.dsl.test_helpers.TestDSLHelpers.test_weak_ref
was failing with
  testtools.matchers._impl.MismatchError: 'weakref' != 'ReferenceType'

This is simply the result of newer Python being more correct about
the name of the weakref ReferenceType.

The fix here is to ask what the name is of the class and use that
instead of the hardcoded 'weakref' name.

Change-Id: I26ea4750f10dedb04a07d188e57fcd391a28f870