Fix versions api by using webob correctly
Currently getting the following error:
TypeError: You cannot set Response.body to a text object (use Response.text)

Closes-Bug: #1882156

Change-Id: Iba918ec671dabb2d0df72e071c6279176c63b312
(cherry picked from commit cd27f95c0bc9bc8941cb6982c788b214253e23ee)